name: Hackernews API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_DB: hn_test
          POSTGRES_PASSWORD: hn123
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt

      - name: Python Linter
        run: pylint hackernews/**/*.py

      - name: Rodar migrations
        run: flask db upgrade
        env:
          FLASK_APP: hackernews.app
          FLASK_ENV: development
          DATABASE_URI: postgresql://postgres:hn123@localhost:5432/hn_test

      - name: Tests
        run: pytest --cache-clear
        env:
          FLASK_APP: hackernews.app
          FLASK_ENV: development
          DATABASE_URI: postgresql://postgres:hn123@localhost:5432/hn_test
